### ISSUE TITLE
🚀 - Seed file

### ISSUE THREAD

**Issue by Delph-Sunny** [davidsaulrodriguez/shop-portal#12]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**
Add a seed file for basic content

**Describe the solution you'd like**
The DB should end up with at least 5 products

**Comment by davidsaulrodriguez** [comment]
This issue was solved with commit https://github.com/davidsaulrodriguez/shop-portal/commit/6d635bb9139234d803a890ddc55129ca867b9dcc
