### ISSUE TITLE
🚀 - Contact Us Page

### ISSUE THREAD

**Issue by Mconway409** [davidsaulrodriguez/shop-portal#13]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**
We want the customers to the e-commerce site to be able to contact the owners of the store with any potential questions or requests, so we are making a "Contact Us" page.

**Describe the solution you'd like**
This page will have fields for the customer to enter their name, email address, and a space for them to state their issue, or ask their question.

**Describe alternatives you've considered**
Having a phone number for the customer to call sometimes works, but with the fields we will put on the page, the contact can be more tailored right off the bat.

**Comment by davidsaulrodriguez** [comment]
Please update the body of this issue. Submitting just the body template is not acceptable.

**Comment by Mconway409** [comment]
Sorry about that David, brain was a bit frazzled when I created it.  The issue has been updated.

**Comment by davidsaulrodriguez** [comment]
This issue was fixed with commit https://github.com/davidsaulrodriguez/shop-portal/commit/c0d5adbbee2c7a4f6efdf686472ed2c59e6a111e
