### ISSUE TITLE
🐞 - schema export incorrect const name

### ISSUE THREAD

**Issue by Delph-Sunny** [davidsaulrodriguez/shop-portal#25]
# 🐞 bug report

the const name is not matching the module export name

**To Reproduce**
NA

**Expected behavior**
matching name

**Comment by davidsaulrodriguez** [comment]
This was recently fixed with a merge commit - https://github.com/davidsaulrodriguez/shop-portal/commit/70bc9b2b9843801314b4a368457e0b99b4dcbd94
