### ISSUE TITLE
🚀 - adding new isReviewed feature for products

### ISSUE THREAD

**Issue by lucpizz** [davidsaulrodriguez/shop-portal#54]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

added configuration files for isReviewed feature.  Files added were model, controller, and api route

**Describe the solution you'd like**

adding a feature to to review products where customers can add stars and comment

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by davidsaulrodriguez** [comment]
This issue was closed with commit https://github.com/davidsaulrodriguez/shop-portal/commit/cc86f4378d80288d61da2c1b5eaccc4e7cf0bdca
